// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umnmvwyxjxswwidueaqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbm12d3l4anhzd3dpZHVlYXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MDY5ODksImV4cCI6MjA1NDk4Mjk4OX0.MFd3GhngQtKLLlMc8hxXP8ijnI5Sjf8pM8Suqb9DMto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);